### PR TITLE
cannot find getter for field

### PR DESCRIPTION
**Pull request by mustafa-da**
A workaround for the "cannot find getter for field" error that occurs while building the project.

### CODE REVIEW

**Comment by kleest** [comment]
What problem should this PR solve? The project builds fine in CI. Could you please show the errors you encounter?

**Comment by roussosalex** [comment]
@mustafa-da is it possible that your system language is set to Turkish or similar? It [seems that](https://stackoverflow.com/a/65058574) the `androidx.room` library has this problem with variable names starting with "i" with some system languages like e.g. Turkish. If so, please try setting your system language to English temporarily and see if that resolves the issue.

**Comment by mustafa-da** [comment]
Ekran Görüntüsü (8)
here is a screenshot.

**Comment by mustafa-da** [comment]
> @mustafa-da is it possible that your system language is set to Turkish or similar? It [seems that](https://stackoverflow.com/a/65058574) the `androidx.room` library has this problem with variable names starting with "i" with some system languages like e.g. Turkish. If so, please try setting your system language to English temporarily and see if that resolves the issue.

did you mean windows system language?

**Comment by roussosalex** [comment]
We updated the `androidx.room` dependency, the problem should be fixed now with any language.

**Pull request closed without merging**
