### PR TITLE
make native libs reproducible

### PR DESCRIPTION
**Pull request by linsui**

### CODE REVIEW

**Review by kleest — APPROVED** [review]

**Review by roussosalex — COMMENTED** [review]
Is there any way these options could be converted into target-specific options, i.e. `target_compile_options` for `-ffile-prefix-map` and `target_link_options` for `--build-id`? I would like to keep all the options in the CMakeLists file if possible.

**Comment by linsui** [comment]
Done.

**Review by roussosalex — APPROVED** [review]

**Comment by linsui** [comment]
Any chance you can update the apk in release so that I can use it for F-Droid reproducible build?

**Comment by kleest** [comment]
Sorry for the late response! Unfortunately that would require creating a new release + tag for just this change so that the release APK really matches the Git tag and commit. I would like to avoid this. Is it possible that you create a release type build locally with your own keys?

**Comment by linsui** [comment]
I need an apk signed by you for reproducible build. This PR makes the apk reproducible. And F-Droid can build the same apk and compare it with yours. If the apk matches your apk then F-Droid publish your apk directly. I guess the next release won't be published soon so I want to add 2.4.0 to F-Droid.

**Comment by kleest** [comment]
Understood. I created [a new release 2.4.1](https://github.com/nfcgate/nfcgate/releases/tag/v2.4.1). Thank you for your efforts in bringing NFCGate to F-Droid!

**Comment by linsui** [comment]
Thanks!

**Pull request merged**
